name: Build site

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: output
          path: output
          if-no-files-found: error
          retention-days: 4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.event_name == 'workflow_dispatch'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: output
          publish_branch: gh-pages
          cname: dhimmel.com